function arrayBufferToBase64(buffer){const bytes=new Uint8Array(buffer);let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk){binary+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(i+chunk,bytes.length)));}return btoa(binary);}
function lowResKeyFromInput(index){const map={4:{key:'ArrowUp',code:'ArrowUp',keyCode:38},5:{key:'ArrowDown',code:'ArrowDown',keyCode:40},6:{key:'ArrowLeft',code:'ArrowLeft',keyCode:37},7:{key:'ArrowRight',code:'ArrowRight',keyCode:39},8:{key:'z',code:'KeyZ',keyCode:90},0:{key:'x',code:'KeyX',keyCode:88},3:{key:'Enter',code:'Enter',keyCode:13}};return map[Number(index)]||null;}
function sendLowResInput(index,value){if(!lowResFrame?.contentWindow)return;const k=lowResKeyFromInput(index);if(!k)return;lowResFrame.contentWindow.postMessage({type:'retro-lowres-key',down:!!value,key:k.key,code:k.code,keyCode:k.keyCode},'*');}
async function launchLowResNx(file,systemId){
  if(loaderInjected){showToast('Le moteur est déjà chargé. NEW recharge Retro Room avant la prochaine ROM.',3000);return;}
  selectedFile=file;currentSystemId=systemId;currentCore='lowresnx';emulatorReady=false;emulatorStarted=false;loaderInjected=true;romName.textContent=file.name.toUpperCase();updateController(systemId);
  setStatus('CHARGEMENT LOWRES NX…');bootScreen.style.display='flex';bootScreen.innerHTML='<b>BRISKO VISION</b><span>CHARGEMENT LOWRES NX</span><span class="tiny">PLAYER WEBASM OFFICIEL • ROM LOCALE</span>';
  try{
    const buffer=await file.arrayBuffer();const romB64=arrayBufferToBase64(buffer);
    const srcdoc=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#000}body{display:flex;align-items:center;justify-content:center}canvas{display:block;width:100%!important;height:100%!important;object-fit:contain;image-rendering:pixelated;background:#000}</style></head><body><canvas id="canvas" tabindex="0" oncontextmenu="event.preventDefault()"></canvas><script>(function(){'use strict';var ROM_B64=${JSON.stringify(romB64)};var binary=atob(ROM_B64);var ROM_BYTES=new Uint8Array(binary.length);for(var i=0;i<binary.length;i++)ROM_BYTES[i]=binary.charCodeAt(i);var BASE=${JSON.stringify(LOWRES_DATA)};window.Module={canvas:document.getElementById('canvas'),arguments:['program.nx'],locateFile:function(path){return BASE+path;},print:function(){},printErr:function(t){parent.postMessage({type:'retro-lowres-log',text:String(t)},'*');},onRuntimeInitialized:function(){try{var original=FS.createPreloadedFile.bind(FS);FS.createPreloadedFile=function(parentDir,name,url,canRead,canWrite,onload,onerror,dontCreateFile,canOwn,preFinish){if(String(url)==='program.nx')return original(parentDir,name,ROM_BYTES,canRead,canWrite,onload,onerror,dontCreateFile,canOwn,preFinish);return original(parentDir,name,url,canRead,canWrite,onload,onerror,dontCreateFile,canOwn,preFinish);};parent.postMessage({type:'retro-lowres-ready'},'*');}catch(err){parent.postMessage({type:'retro-lowres-error',text:String(err&&err.message||err)},'*');}}};function fireKey(data){var type=data.down?'keydown':'keyup';var ev;try{ev=new KeyboardEvent(type,{key:data.key,code:data.code,bubbles:true,cancelable:true});try{Object.defineProperty(ev,'keyCode',{get:function(){return data.keyCode;}});}catch(_){}try{Object.defineProperty(ev,'which',{get:function(){return data.keyCode;}});}catch(_){}}catch(_){ev=document.createEvent('Event');ev.initEvent(type,true,true);ev.key=data.key;ev.code=data.code;ev.keyCode=data.keyCode;ev.which=data.keyCode;}document.dispatchEvent(ev);window.dispatchEvent(ev);var c=document.getElementById('canvas');if(c)c.dispatchEvent(ev);}addEventListener('message',function(e){if(e.data&&e.data.type==='retro-lowres-key')fireKey(e.data);});document.addEventListener('keydown',function(e){if([37,38,39,40].indexOf(e.keyCode)>=0)e.preventDefault();},false);})();<\/script><script async src="${LOWRES_JS}"><\/script></body></html>`;
    gameDiv.innerHTML='';lowResFrame=document.createElement('iframe');lowResFrame.className='lowresFrame';lowResFrame.setAttribute('allow','autoplay; fullscreen');lowResFrame.setAttribute('title','LowRes NX');lowResFrame.srcdoc=srcdoc;gameDiv.appendChild(lowResFrame);
    watchdog=setTimeout(()=>{if(emulatorReady||emulatorStarted)return;setStatus('LOWRES NX NE RÉPOND PAS');showToast('Le player LowRes NX n’a pas démarré. Vérifie la connexion au player WebAssembly.',5500);},30000);
  }catch(err){loaderInjected=false;currentCore=null;setStatus('ERREUR LOWRES NX');bootScreen.innerHTML='<b>ERREUR LOWRES NX</b><span>LECTURE DE LA ROM IMPOSSIBLE</span>';showToast(String(err&&err.message||err),5000);}
}
window.addEventListener('message',e=>{if(e.source!==lowResFrame?.contentWindow||!e.data)return;if(e.data.type==='retro-lowres-ready'){emulatorReady=true;emulatorStarted=true;clearTimeout(watchdog);bootScreen.style.display='none';setStatus('PLAY — LOWRES NX');romBtn.textContent='NEW';showToast('LowRes NX prêt');}else if(e.data.type==='retro-lowres-error'){clearTimeout(watchdog);setStatus('ERREUR LOWRES NX');showToast('LowRes NX : '+String(e.data.text||'erreur inconnue'),6000);}});
